GET http://localhost:8080/tracerData



###
POST localhost:8080/searchTracerData
Content-Type: application/json

{
  "category": "용역",
  "bidder": ["한국사회보장정보원", "대검찰청", "한국출판문화산업진흥원", "한국환경산업기술원", "정보통신산업진흥원", "인사혁신처", "소상공인시장진흥공단",
    "공정거래위원회", "한국공정거래조정원", "한국국토정보공사", "한국여성인권진흥원", "인천공항공사", "산림청",
    "산림교육원", "문화재청", "문화체육관광부", "SBA", "서울산업진흥원", "축산물품질평가원", "질병관리본부",
    "기초과학연구원", "연구개발특구진흥재단", "서울신용보증재단", "방송통신위원회", "한국관광공사", "법무부",
    "여성가족부", "국회사무처", "국방정보본부", "태권도진흥재단", "보건복지부", "외교부"],
  "titleLinkText": ["유지", "시스템", "운영", "유지관리", "유지보수", "고도화", "플랫폼", "산림청", "솔루션", "챗봇"],
  "startDate": "2023-12-11",
  "endDate": "2023-12-25"

}

###
bidder와 titleLinkText는 화면에서 전달받는다.